version: '3.8'
services:
  db:
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=112233
      - POSTGRES_DB=hw_processor

  api:
    image: homework-processor
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hw_processor
    ports:
      - "8080:8080"
    depends_on:
      - db